// Generated by Tekla.Technology.Akit.ScriptBuilder



namespace Tekla.Technology.Akit.UserScript
{
    public class Script
    {
        public static void Run(Tekla.Technology.Akit.IScript akit)
        {
            System.Threading.Thread.Sleep(20000); // wait for 20 sec (20000 ms). This is sometimes needed to get the environment ready for model sharing. Try to increase if there are read-in issues.
            akit.Callback("acmdRunPluginMethod", "SharingToolsFeature;Tool.SharingAutomation;r0.00:00:00", "main_frame");
            System.Threading.Thread.Sleep(20000); // wait for 20 sec (20000 ms). This is sometimes needed to allow the read-in to fully complete. Try to increase if there are read-in/save issues.
            akit.Callback("acmd_save_model", "", "main_frame");
        }
    }
}
